### ISSUE TITLE
Looking forward for your running code to try

### ISSUE THREAD

**Issue by garimss** [dancek/thesis#1]
Do you have any running code for this too?

**Comment by dancek** [comment]
@garimss it's been seven years and I didn't have anything really useful even back then. Kinect Fusion was state of the art, and there was the `kinfu` open source implementation. Of course only useful for scanning static objects. I think current SDKs include better samples than my code ever was.

I'm sure much more advanced research exists these days; I was mainly trying different simple approaches (with bad results).

**Comment by dancek** [comment]
I'm quite sure I don't have the code anymore but if you really want code related to a specific subchapter, just ask and I'll see what I can do.
